#! /usr/bin/bash

source ./table_management

table_menu(){
echo "Connected To Database: $1"
DB_NAME=$1
    while true; 
    do
        echo -e "\nTable Operations Menu:"
        echo "1) Create Table"
        echo "2) List Tables"
        echo "3) Drop Table"
        echo "4) Rename Table"
        echo "5) Insert Into Table"
        echo "6) Select from Table"
        echo "7) Delete from Table"
        echo "8) Update Table"
        echo "9) Disconnect from Database"

        # Read user input with validation
        while true; do
            read -p "Select an Option (1-9): " option
            # Validate if input is a number between 1 and 9
            if [[ "$option" =~ ^[1-9]$ ]]; then
                break
            else
                echo "Please enter a valid number between 1 and 9"
            fi
        done
                        
        case $option in
            1) create_table "$DB_NAME" ;;
            2) list_tables "$DB_NAME" ;;
            3) drop_table "$DB_NAME" ;;
            4) rename_table "$DB_NAME" ;;
            5) insert_into_table "$DB_NAME" ;;
            6) select_from_table "$DB_NAME" ;;
            7) delete_from "$DB_NAME" ;;
            8) update_table "$DB_NAME" ;;
            9) 
                echo "Disconnected from Database: $DB_NAME"
                break 
                ;;
            *) echo "Invalid Option, Please Try Again." ;;
        esac
    done

}
# table_menu